
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-04
owner: ucsb-cs156-f24
repo_name: team02-f24-04
pull_requests: [{"author":{"id":"U_kgDOBdHjhg","is_bot":false,"login":"michaelhu88","name":""},"headRefName":"Michael-HelpRequestEnd2End","number":137,"title":"Michael help request end2 end","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/137"},{"author":{"id":"U_kgDOBdHjhg","is_bot":false,"login":"michaelhu88","name":""},"headRefName":"Michael-Team03","number":136,"title":"Michael team03","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/136"}]
