
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-04
owner: ucsb-cs156-f24
repo_name: team02-f24-04
pull_requests: [{"author":{"id":"U_kgDOBdHjhg","is_bot":false,"login":"michaelhu88","name":""},"headRefName":"Michael-CopyHelpRequest","number":83,"title":"copied team01 files over","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/83"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"UCSBOrganization-form","number":79,"title":"UCSBOrganization: form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/79"},{"author":{"id":"U_kgDOBtyGZQ","is_bot":false,"login":"nikhilvyas109","name":""},"headRefName":"Nikhil-MenuItemFormComponent","number":72,"title":"Dining Menu Items Form Component","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/72"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"UCSBOrganization-fixtures","number":68,"title":"UCSBOrganization: added fixtures","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/68"}]
