
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-04
owner: ucsb-cs156-f24
repo_name: team02-f24-04
pull_requests: [{"author":{"id":"U_kgDOBdHjhg","is_bot":false,"login":"michaelhu88","name":""},"headRefName":"Michael-HelpRequestEditPage","number":117,"title":"Michael help request edit page","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/117"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"UCSBOrganization-newPlaceholders","number":113,"title":"UCSBOrganization: updated placeholders","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/113"},{"author":{"id":"MDQ6VXNlcjU5MzgzNTk1","is_bot":false,"login":"alvinwang1","name":"Alvin Wang"},"headRefName":"Alvin-RecommendationRequest-edit","number":112,"title":"Alvin - Recommendation Request - edit","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/112"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"UCSBOrganization-editPage","number":107,"title":"UCSBOrganization: edit page","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/107"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"UCSBOrganization-indexPage","number":104,"title":"UCSBOrganization: index page","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/104"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"UCSBOrganization-createPage","number":103,"title":"UCSBOrganization: create page","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/103"},{"author":{"id":"MDQ6VXNlcjU5MzgzNTk1","is_bot":false,"login":"alvinwang1","name":"Alvin Wang"},"headRefName":"Alvin-RecommendationRequest-indexpage","number":102,"title":"Alvin - Recommendation Request - Indexpage","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/102"},{"author":{"id":"U_kgDOBphJeQ","is_bot":false,"login":"qwaszxjack","name":"Jackie Chen"},"headRefName":"UCSBOrganization-placeholders","number":96,"title":"UCSBOrganization: placeholders","url":"https://github.com/ucsb-cs156-f24/team02-f24-04/pull/96"}]
